# Generated by Django 2.1.7 on 2019-02-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referrals',
            new_name='Referral',
        ),
    ]
